on: push
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: Publish to www.sanctuarycrew.com
        # If (nr) appears in the commit, don't regenerate the site via git
        if: "!contains(github.event.head_commit.message, '(nr)')"
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mkdir -p ~/.ssh
          cp /root/.ssh/* ~/.ssh/ 2> /dev/null || true
          RESPONSE=$(${{ secrets.SC_SSH_REBUILDCOMMAND }} 2>&1 |tee >(cat 1>&2) | grep "Error" || true)
          if ([[ $RESPONSE = *Error* ]]) then exit 1; fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SC_SSH_PRIVATEKEY }}
